"""Canonical ledger event taxonomy for Phase-4 runtime."""

_ACTION = "ACTION"

EVENT_TYPES = frozenset(
    {
        f"{_ACTION}_ATTEMPTED",
        f"{_ACTION}_COMPLETED",
        "SEARCH_QUERY",
        "WEBPAGE_LAUNCH",
        "WEBPAGE_PREVIEW",
        "EXTERNAL_NETWORK_CALL",
        "NETWORK_CALL_FAILED",
        "MODEL_NETWORK_CALL",
        "MODEL_NETWORK_CALL_FAILED",
        "MODEL_UPDATED",
        "SPEECH_RENDERED",
        "CAPABILITY_PROFILE_APPLIED",
        "CAPABILITY_INSTALLED",
        "EXECUTION_TIMEOUT",
        "EXECUTION_MEMORY_EXCEEDED",
        "EXECUTION_CPU_EXCEEDED",
        "COGNITIVE_ANALYSIS_STARTED",
        "COGNITIVE_ANALYSIS_COMPLETED",
        "CONTEXT_SNAPSHOT_REQUESTED",
        "CONTEXT_SNAPSHOT_COMPLETED",
        "SCREEN_CAPTURE_REQUESTED",
        "SCREEN_CAPTURE_COMPLETED",
        "SCREEN_ANALYSIS_COMPLETED",
        "EXPLAIN_ANYTHING_REQUESTED",
        "EXPLAIN_ANYTHING_COMPLETED",
        "WORKING_CONTEXT_CREATED",
        "WORKING_CONTEXT_UPDATED",
        "WORKING_CONTEXT_PRUNED",
        "WORKING_CONTEXT_CONSUMED",
    }
)
