window.NOVA_DASHBOARD_CONFIG = {
  API_BASE: `${window.location.protocol}//${window.location.host}`,
  WS_BASE: `${window.location.protocol === "https:" ? "wss" : "ws"}://${window.location.host}`,
  HEY_NOVA_WAKE_WORD: "Hey Nova",
  STORAGE_KEYS: {
    firstRunDone: "nova_first_run_done",
    quickActions: "nova_quick_actions",
    hintsExpanded: "nova_hints_expanded",
    uiLargeText: "nova_ui_large_text",
    uiHighContrast: "nova_ui_high_contrast",
    uiCompactDensity: "nova_ui_compact_density",
    voiceWakeWordEnabled: "nova_voice_wake_word_enabled",
    activePage: "nova_active_page",
    morningExpanded: "nova_morning_expanded",
    setupMode: "nova_setup_mode",
  },
  PAGE_LABELS: {
    chat: "Chat",
    news: "News",
    intro: "Intro",
    home: "Home",
    agent: "Agent",
    workspace: "Workspace",
    memory: "Memory",
    policy: "Policies",
    trust: "Trust",
    settings: "Settings",
  },
  PRIMARY_NAV_ITEMS: [
    { page: "chat", label: "Chat" },
    { page: "home", label: "Home" },
    { page: "agent", label: "Agent" },
    { page: "news", label: "News" },
    { page: "workspace", label: "Workspace" },
    { page: "memory", label: "Memory" },
    { page: "policy", label: "Policies" },
    { page: "trust", label: "Trust" },
    { page: "settings", label: "Settings" },
    { page: "intro", label: "Intro" },
  ],
  MORNING_FALLBACK_TIMEOUT_MS: 4500,
  QUICK_ACTIONS_BY_PAGE: {
    chat: [
      { id: "chat_plan_goal", label: "Plan this goal", command: "help me do this" },
      { id: "chat_build_page", label: "Build a page", command: "build me a landing page for my business" },
      { id: "chat_research", label: "Research a topic", command: "research latest technology news" },
      { id: "chat_explain", label: "Explain what I'm seeing", command: "explain this" },
      { id: "chat_brief", label: "Plan my day", command: "daily brief" },
      { id: "chat_threads", label: "Continue a project", command: "show threads" },
      { id: "chat_thread_status", label: "Check project status", command: "project status this" },
      { id: "chat_thread_memory", label: "Review project memory", command: "memory list thread this" },
      { id: "chat_memory_overview", label: "Review saved memory", command: "memory overview" },
      { id: "chat_schedules", label: "Review reminders", command: "show schedules" },
      { id: "chat_patterns", label: "Review patterns", command: "pattern status" },
      { id: "chat_system", label: "System status", command: "system status" },
      { id: "chat_tone", label: "Tone settings", command: "tone status" },
      { id: "chat_doc_create", label: "Create analysis doc", command: "create analysis report on global technology policy updates" },
      { id: "chat_doc_list", label: "Open analysis docs", command: "list analysis docs" },
    ],
    news: [
      { id: "news_get", label: "Get headlines", command: "news", stayOnPage: true },
      { id: "news_sum", label: "Source brief", command: "today's news", switchToPage: "chat" },
      { id: "news_brief", label: "Daily brief", command: "daily brief", stayOnPage: true },
      { id: "news_compare", label: "Compare stories", command: "compare headlines 1 and 2", stayOnPage: true },
      { id: "news_explain_page", label: "Explain this page", command: "what is this page" },
    ],
    intro: [
      { id: "intro_home", label: "Open Home", switchToPage: "home", command: "workspace home", stayOnPage: true },
      { id: "intro_workspace", label: "Open Workspace", switchToPage: "workspace", command: "workspace board", stayOnPage: true },
      { id: "intro_trust", label: "Open Trust", switchToPage: "trust", command: "trust center", stayOnPage: true },
      { id: "intro_settings", label: "Open Settings", switchToPage: "settings", command: "voice status", stayOnPage: true },
      { id: "intro_magic", label: "Try Explain This", command: "explain this", switchToPage: "chat" },
    ],
    home: [
      { id: "home_system", label: "System status", command: "system status", switchToPage: "chat" },
      { id: "home_calendar", label: "Calendar", command: "calendar", switchToPage: "chat" },
      { id: "home_weather", label: "Weather", command: "weather", switchToPage: "chat" },
      { id: "home_agent", label: "Home agent", command: "bridge status", switchToPage: "agent", stayOnPage: true },
      { id: "home_explain", label: "Explain this", command: "explain this", switchToPage: "chat" },
      { id: "home_capture", label: "Analyze screen", command: "analyze this screen", switchToPage: "chat", prefill: true },
      { id: "home_threads", label: "Show threads", command: "show threads", switchToPage: "chat" },
      { id: "home_thread_status", label: "Project status", command: "project status this", switchToPage: "chat" },
      { id: "home_most_blocked", label: "Most blocked", command: "which project is most blocked right now", switchToPage: "chat" },
      { id: "home_memory_overview", label: "Memory overview", command: "memory overview", switchToPage: "memory" },
      { id: "home_tone", label: "Tone settings", command: "tone status", switchToPage: "chat" },
      { id: "home_schedules", label: "Schedules", command: "show schedules", switchToPage: "chat" },
      { id: "home_patterns", label: "Pattern review", command: "pattern status", switchToPage: "chat" },
    ],
    workspace: [
      { id: "workspace_board", label: "Workspace board", command: "workspace board", stayOnPage: true },
      { id: "workspace_threads", label: "Show threads", command: "show threads", switchToPage: "chat" },
      { id: "workspace_status", label: "Project status", command: "project status this", switchToPage: "chat" },
      { id: "workspace_visual", label: "Structure map", command: "show structure map", stayOnPage: true },
      { id: "workspace_architecture", label: "Architecture report", command: "create analysis report on this repo architecture", switchToPage: "chat" },
    ],
    agent: [
      { id: "agent_refresh", label: "Refresh agent", command: "bridge status", stayOnPage: true },
      { id: "agent_settings", label: "Settings", command: "connection status", switchToPage: "settings", stayOnPage: true },
      { id: "agent_trust", label: "Trust", command: "trust center", switchToPage: "trust", stayOnPage: true },
      { id: "agent_brief", label: "Morning brief", command: "daily brief", switchToPage: "chat" },
    ],
    memory: [
      { id: "memory_page_overview", label: "Overview", command: "memory overview", stayOnPage: true },
      { id: "memory_page_list", label: "List memory", command: "list memories", switchToPage: "chat" },
      { id: "memory_page_threads", label: "Thread memory", command: "memory list thread this", switchToPage: "chat" },
      { id: "memory_page_save", label: "Save decision", command: "memory save decision for deployment issue: verify next step", switchToPage: "chat" },
    ],
    policy: [
      { id: "policy_page_overview", label: "Refresh drafts", command: "policy overview", stayOnPage: true },
      { id: "policy_page_calendar", label: "Create calendar draft", command: "policy create weekday calendar snapshot at 8:00 am", stayOnPage: true },
      { id: "policy_page_weather", label: "Create weather draft", command: "policy create daily weather snapshot at 7:30 am", stayOnPage: true },
      { id: "policy_page_trust", label: "Trust center", command: "trust center", switchToPage: "trust", stayOnPage: true },
    ],
    trust: [
      { id: "trust_refresh", label: "Refresh trust", command: "trust center", stayOnPage: true },
      { id: "trust_system", label: "System status", command: "system status", switchToPage: "chat" },
      { id: "trust_memory", label: "Memory overview", command: "memory overview", switchToPage: "memory" },
      { id: "trust_agent", label: "Agent", command: "bridge status", switchToPage: "agent", stayOnPage: true },
      { id: "trust_workspace", label: "Open Home", command: "workspace home", switchToPage: "home", stayOnPage: true },
      { id: "trust_policies", label: "Policies", command: "policy overview", switchToPage: "policy", stayOnPage: true },
      { id: "trust_bridge", label: "Bridge status", command: "bridge status", stayOnPage: true },
      { id: "trust_settings", label: "Settings", command: "voice status", switchToPage: "settings", stayOnPage: true },
    ],
    settings: [
      { id: "settings_voice", label: "Voice status", command: "voice status", switchToPage: "chat" },
      { id: "settings_voice_check", label: "Voice check", command: "voice check", switchToPage: "chat" },
      { id: "settings_agent", label: "Agent", command: "bridge status", switchToPage: "agent", stayOnPage: true },
      { id: "settings_connections", label: "Connections", command: "connection status", stayOnPage: true },
      { id: "settings_trust", label: "Trust center", command: "trust center", switchToPage: "trust", stayOnPage: true },
      { id: "settings_policies", label: "Policies", command: "policy overview", switchToPage: "policy", stayOnPage: true },
      { id: "settings_intro", label: "Introduction", switchToPage: "intro", command: "workspace home", stayOnPage: true },
    ],
  },
  COMMAND_SUGGESTIONS: [
    // Everyday goals (outcome-first)
    "build me a landing page for my business",
    "help me turn this idea into a plan",
    "plan my day",
    "research latest technology news",
    "summarize today's headlines",
    "explain this",
    "help me do this",
    "why this recommendation",
    "which one should I download",
    "search for local weather alerts",
    // Continue work
    "continue where I left off",
    "what was I working on",
    "which project needs attention",
    "what are my biggest blockers",
    "save this decision",
    // News and research
    "summarize politics news",
    "summarize global news",
    "summarize crypto news",
    "summary of article 1",
    "update tracked stories",
    "create analysis report on AI regulation",
    // Daily setup
    "show my schedule",
    "remind me at 2:00 pm to check in",
    "schedule daily brief at 8:00 am",
    "check my calendar",
    // System
    "system status",
    "open documents",
    "speak that",
    "volume up",
    "brightness down",
    "play",
    "pause",
    // Power user (syntax commands — kept for discoverability)
    "show threads",
    "workspace home",
    "workspace board",
    "memory overview",
    "tone status",
    "pattern status",
    "trust center",
    "policy overview",
    "connection status",
    "voice status",
  ],
  HELP_EXAMPLES: [
    // Start here — everyday goals
    "plan my day",
    "summarize today's headlines",
    "explain this",
    "help me do this",
    "why this recommendation",
    "which one should I download",
    "research a topic",
    // Continue work
    "continue where I left off",
    "what was I working on",
    "which project needs attention",
    "save this decision",
    // News and research
    "summarize politics news",
    "summarize global news",
    "create analysis report on AI regulation",
    "search for eclipse dates",
    "update tracked stories",
    // Scheduling
    "show my schedule",
    "schedule daily brief at 8:00 am",
    "remind me daily at 9:00 am to check in",
    // System and voice
    "system status",
    "open documents",
    "speak that",
    "set volume 40",
    "set brightness 50",
    // Advanced — Nova syntax
    "memory overview",
    "tone status",
    "tone set concise",
    "pattern status",
    "review patterns",
    "show threads",
    "workspace board",
    "trust center",
  ],
  COMMAND_DISCOVERY_GROUPS: [
    { label: "Get started", commands: ["plan my day", "summarize today's headlines", "explain this"] },
    { label: "Research", commands: ["research a topic", "create analysis report on AI regulation", "search for eclipse dates"] },
    { label: "Help me decide", commands: ["help me do this", "why this recommendation", "which one should I download"] },
    { label: "Continue work", commands: ["continue where I left off", "what was I working on", "which project needs attention"] },
    { label: "Remember things", commands: ["save this decision", "memory overview", "what do I know about this"] },
    { label: "Response style", commands: ["tone status", "tone set concise", "tone set research detailed"] },
    { label: "Schedules", commands: ["show my schedule", "schedule daily brief at 8:00 am", "remind me at 2:00 pm to check in"] },
    { label: "Patterns", commands: ["pattern status", "review patterns", "what patterns have you noticed"] },
    { label: "System", commands: ["system status", "open documents", "volume up"] },
  ],
  LONG_MESSAGE_CHAR_LIMIT: 280,
  LONG_MESSAGE_LINE_LIMIT: 4,
  LONG_MESSAGE_SENTENCE_LIMIT: 2,
  URL_PATTERN: /(https?:\/\/[^\s<]+)/gi,
  WIDGET_HYDRATE_MIN_INTERVAL_MS: 15000,
  WIDGET_AUTO_REFRESH_INTERVAL_MS: 5 * 60 * 1000,
};

