window.NOVA_DASHBOARD_CONFIG = {
  // Task 1.3: default first-run prompt pushed toward a quick "magic moment".
  FIRST_RUN_DEFAULT_PROMPT: "daily brief",
  API_BASE: `${window.location.protocol}//${window.location.host}`,
  WS_BASE: `${window.location.protocol === "https:" ? "wss" : "ws"}://${window.location.host}`,
  HEY_NOVA_WAKE_WORD: "Hey Nova",
  STORAGE_KEYS: {
    firstRunDone: "nova_first_run_done",
    quickActions: "nova_quick_actions",
    hintsExpanded: "nova_hints_expanded",
    uiLargeText: "nova_ui_large_text",
    uiHighContrast: "nova_ui_high_contrast",
    uiCompactDensity: "nova_ui_compact_density",
    voiceWakeWordEnabled: "nova_voice_wake_word_enabled",
    activePage: "nova_active_page",
    morningExpanded: "nova_morning_expanded",
    setupMode: "nova_setup_mode",
  },
  PAGE_LABELS: {
    chat: "Chat",
    news: "News",
    intro: "Intro",
    home: "Home",
    agent: "Agent",
    workspace: "Workspace",
    goals: "Goals",
    memory: "Memory",
    policy: "Rules",
    trust: "Activity & Receipts",
    settings: "Settings",
  },
  PRIMARY_NAV_ITEMS: [
    { page: "home", label: "Home" },
    { page: "chat", label: "Chat" },
    { page: "goals", label: "Goals" },
    { page: "news", label: "News" },
    { page: "settings", label: "Settings" },
  ],
  SECONDARY_NAV_ITEMS: [],
  ADVANCED_NAV_ITEMS: [
    { page: "trust", label: "Activity & Receipts", summary: "Receipts, blocked actions, runtime health, and proof." },
    { page: "agent", label: "Agent" },
    { page: "policy", label: "Rules" },
    { page: "workspace", label: "Workspace" },
    { page: "memory", label: "Memory" },
    { page: "intro", label: "Intro" },
  ],
  MORNING_FALLBACK_TIMEOUT_MS: 4500,
  QUICK_ACTIONS_BY_PAGE: {
    chat: [
      { id: "chat_brief", label: "Daily brief", command: "daily brief" },
      { id: "chat_research", label: "Research a topic", command: "research latest technology news" },
      { id: "chat_explain", label: "Explain what I'm seeing", command: "explain this" },
      { id: "chat_threads", label: "Continue a project", command: "show threads" },
      { id: "chat_plan_goal", label: "Help me plan", command: "help me make a plan for this" },
    ],
    news: [
      { id: "news_get", label: "Get headlines", command: "news", stayOnPage: true },
      { id: "news_sum", label: "Source brief", command: "today's news", switchToPage: "chat" },
      { id: "news_brief", label: "Daily brief", command: "daily brief", stayOnPage: true },
      { id: "news_explain_page", label: "Explain this page", command: "what is this page" },
    ],
    intro: [
      { id: "intro_home", label: "Open Home", switchToPage: "home", command: "workspace home", stayOnPage: true },
      { id: "intro_workspace", label: "Open Workspace", switchToPage: "workspace", command: "workspace board", stayOnPage: true },
      { id: "intro_trust", label: "Open Trust", switchToPage: "trust", command: "trust center", stayOnPage: true },
      { id: "intro_settings", label: "Open Settings", switchToPage: "settings", command: "voice status", stayOnPage: true },
      { id: "intro_magic", label: "Try Explain This", command: "explain this", switchToPage: "chat" },
    ],
    home: [
      { id: "home_brief", label: "Daily brief", command: "daily brief", switchToPage: "chat" },
      { id: "home_calendar", label: "Today's schedule", command: "calendar", switchToPage: "chat", requires: "calendar_connected" },
      { id: "home_weather", label: "Weather", command: "weather", switchToPage: "chat" },
      { id: "home_explain", label: "Explain this", command: "explain this", switchToPage: "chat" },
      { id: "home_threads", label: "Continue a project", command: "show threads", switchToPage: "chat" },
      { id: "home_system", label: "System status", command: "system status", switchToPage: "chat" },
    ],
    workspace: [
      { id: "workspace_board", label: "Open workspace", command: "workspace board", stayOnPage: true },
      { id: "workspace_threads", label: "Show threads", command: "show threads", switchToPage: "chat" },
      { id: "workspace_status", label: "Project status", command: "project status this", switchToPage: "chat" },
      { id: "workspace_visual", label: "Structure map", command: "show structure map", stayOnPage: true },
      { id: "workspace_architecture", label: "Architecture report", command: "create analysis report on this repo architecture", switchToPage: "chat" },
    ],
    agent: [
      { id: "agent_refresh", label: "Refresh agent", command: "bridge status", stayOnPage: true },
      { id: "agent_settings", label: "Settings", command: "connection status", switchToPage: "settings", stayOnPage: true },
      { id: "agent_trust", label: "Trust", command: "trust center", switchToPage: "trust", stayOnPage: true },
      { id: "agent_brief", label: "Daily brief", command: "daily brief", switchToPage: "chat" },
    ],
    memory: [
      { id: "memory_page_overview", label: "Overview", command: "memory overview", stayOnPage: true },
      { id: "memory_page_list", label: "List memory", command: "list memories", switchToPage: "chat" },
      { id: "memory_page_threads", label: "Thread memory", command: "memory list thread this", switchToPage: "chat" },
      { id: "memory_page_save", label: "Save decision", command: "memory save decision for deployment issue: verify next step", switchToPage: "chat" },
    ],
    policy: [
      { id: "policy_page_overview", label: "Refresh rules", command: "policy overview", stayOnPage: true },
      { id: "policy_page_calendar", label: "Draft calendar rule", command: "policy create weekday calendar snapshot at 8:00 am", stayOnPage: true },
      { id: "policy_page_weather", label: "Draft weather rule", command: "policy create daily weather snapshot at 7:30 am", stayOnPage: true },
      { id: "policy_page_trust", label: "Trust center", command: "trust center", switchToPage: "trust", stayOnPage: true },
    ],
    trust: [
      { id: "trust_refresh", label: "Refresh trust", command: "trust center", stayOnPage: true },
      { id: "trust_system", label: "System status", command: "system status", switchToPage: "chat" },
      { id: "trust_memory", label: "Memory overview", command: "memory overview", switchToPage: "memory" },
      { id: "trust_agent", label: "Agent", command: "bridge status", switchToPage: "agent", stayOnPage: true },
      { id: "trust_workspace", label: "Open Home", command: "workspace home", switchToPage: "home", stayOnPage: true },
      { id: "trust_policies", label: "Rules", command: "policy overview", switchToPage: "policy", stayOnPage: true },
      { id: "trust_bridge", label: "Bridge status", command: "bridge status", stayOnPage: true },
      { id: "trust_settings", label: "Settings", command: "voice status", switchToPage: "settings", stayOnPage: true },
    ],
    settings: [
      { id: "settings_voice", label: "Voice status", command: "voice status", switchToPage: "chat" },
      { id: "settings_voice_check", label: "Voice check", command: "voice check", switchToPage: "chat" },
      { id: "settings_connections", label: "Connections", command: "connection status", stayOnPage: true },
    ],
  },
  COMMAND_SUGGESTIONS: [
    // Everyday goals (outcome-first, truth-scoped)
    "help me make a plan for this",
    "help me plan my day",
    "research latest technology news",
    "summarize today's headlines",
    "explain this",
    "help me think through the next steps",
    "search for local weather alerts",
    // Continue work
    "show threads",
    "save this decision",
    // News and research
    "summarize politics news",
    "summarize global news",
    "summarize crypto news",
    "summary of article 1",
    "update tracked stories",
    "create analysis report on AI regulation",
    // User-directed scheduling
    "remind me at 2:00 pm to check in",
    "schedule daily brief at 8:00 am",
    // System
    "system status",
    "open documents",
    "speak that",
  ],
  HELP_EXAMPLES: [
    // Start here — everyday goals
    "help me plan my day",
    "summarize today's headlines",
    "explain this",
    "help me make a plan for this",
    "research a topic",
    // Continue work
    "show threads",
    "save this decision",
    // News and research
    "summarize politics news",
    "summarize global news",
    "create analysis report on AI regulation",
    "search for eclipse dates",
    "update tracked stories",
    // User-directed scheduling
    "schedule daily brief at 8:00 am",
    "remind me daily at 9:00 am to check in",
    // System and voice
    "system status",
    "open documents",
    "speak that",
  ],
  COMMAND_DISCOVERY_GROUPS: [
    { label: "Get started", commands: ["daily brief", "summarize today's headlines", "explain this"] },
    { label: "Research", commands: ["research a topic", "create analysis report on AI regulation", "search for eclipse dates"] },
    { label: "Plan and decide", commands: ["help me make a plan for this", "help me plan my day"] },
    { label: "Continue work", commands: ["show threads"] },
    { label: "Remember things", commands: ["save this decision", "what do I know about this"] },
    { label: "Schedules", commands: ["schedule daily brief at 8:00 am", "remind me at 2:00 pm to check in"] },
    { label: "System", commands: ["system status", "open documents"] },
  ],
  LONG_MESSAGE_CHAR_LIMIT: 280,
  LONG_MESSAGE_LINE_LIMIT: 4,
  LONG_MESSAGE_SENTENCE_LIMIT: 2,
  URL_PATTERN: /(https?:\/\/[^\s<]+)/gi,
  WIDGET_HYDRATE_MIN_INTERVAL_MS: 15000,
  WIDGET_AUTO_REFRESH_INTERVAL_MS: 5 * 60 * 1000,
};
