"""Generate an Obsidian overlay for the Nova repository.

The repository root acts as the vault so docs and code can appear in the same
graph. This script generates:

- .obsidian/  local vault config (gitignored)
- _MOCs/      tracked map-of-content notes for docs and code navigation

Source files are never modified.
"""
from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = REPO_ROOT / "docs"
AUTOMATIONS_ROOT = REPO_ROOT / "automations"
VAULT_CONFIG_DIR = REPO_ROOT / ".obsidian"
MOC_DIR = REPO_ROOT / "_MOCs"

GENERATED_MARKER = (
    "<!-- GENERATED BY scripts/generate_obsidian_overlay.py "
    "- DO NOT EDIT: re-run the script to refresh. -->"
)

NOTE_SUFFIXES = {".md", ".txt"}
CODE_SUFFIXES = {".py", ".js", ".html", ".css", ".json", ".yaml", ".yml", ".toml"}
AUTOMATION_SUFFIXES = NOTE_SUFFIXES | {".toml"}
ASSET_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".jsonl", ".pid", ".log", ".example"}

SKIP_DIR_NAMES = {
    "_MOCs",
    ".obsidian",
    ".git",
    ".claude",
    ".claire",
    ".venv",
    "venv",
    "node_modules",
    "__pycache__",
    "dist",
    "build",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "coverage",
    "htmlcov",
}

CATEGORIES: list[tuple[str, str, str, list[str]]] = [
    ("phase", "Phases", "#4F8AD8", ["path:docs/design/Phase"]),
    (
        "governance",
        "Governance",
        "#D8504F",
        [
            "path:docs/GOVERNANCE",
            "path:docs/canonical",
            "path:docs/canon",
            "path:nova_backend/src/governor",
            "path:nova_backend/src/governance",
        ],
    ),
    (
        "runtime",
        "Runtime and ops",
        "#4FB56B",
        [
            "path:docs/current_runtime",
            "path:docs/runtime",
            "path:nova_backend/src/runtime",
            "path:nova_backend/src/audit",
            "path:nova_backend/src/openclaw",
        ],
    ),
    (
        "frontend",
        "Frontend",
        "#4FC9D8",
        ["path:nova_backend/static", "path:Nova-Frontend-Dashboard"],
    ),
    ("tests", "Tests", "#D8D14F", ["path:docs/testing", "path:nova_backend/tests"]),
    (
        "scripts",
        "Scripts and tools",
        "#E58BD8",
        ["path:scripts", "path:docs/tools", "path:automations"],
    ),
    ("design", "Design specs", "#B56BD8", ["path:docs/design"]),
    ("proofs", "Proofs", "#D8A64F", ["path:docs/PROOFS"]),
    (
        "reference",
        "Reference",
        "#9AA0A6",
        [
            "path:docs/reference",
            "path:README.md",
            "path:REPO_MAP.md",
            "path:CONTRIBUTING.md",
            "path:SECURITY.md",
            "path:_MOCs",
        ],
    ),
    ("archive", "Archive", "#6B6E73", ["path:docs/archive", "path:archive"]),
]

CATEGORY_ORDER = [cat_id for cat_id, *_rest in CATEGORIES]
CATEGORY_LABELS = {cat_id: label for cat_id, label, *_rest in CATEGORIES}
CATEGORY_COLORS = {cat_id: color for cat_id, _label, color, _queries in CATEGORIES}
CATEGORY_QUERIES = {cat_id: queries for cat_id, _label, _color, queries in CATEGORIES}

TITLE_HEADING_RE = re.compile(r"^\s{0,3}#\s+(.+?)\s*$", re.MULTILINE)
PHASE_DIR_RE = re.compile(r"^Phase[\s._-]*([0-9]+(?:\.[0-9]+)?)$", re.IGNORECASE)
PHASE_FILE_RE = re.compile(r"phase[\s._-]*([0-9]+(?:\.[0-9]+)?)", re.IGNORECASE)

TOPIC_KEYWORDS: dict[str, tuple[str, ...]] = {
    "governance": ("governance", "governor", "bypass", "authority boundary"),
    "openclaw": ("openclaw", "home agent", "project_snapshot"),
    "voice": ("voice", "stt", "wake", "speech"),
    "memory": ("memory", "continuity", "working context", "saved"),
    "ux": ("dashboard", "usability", "friction", "onboarding", "workspace"),
    "runtime": ("runtime state", "current runtime", "runtime fingerprint", "bridge"),
    "testing": ("test", "verification"),
    "architecture": ("architecture", "diagram", "system process", "matrix"),
}

TOPIC_PATH_HINTS: dict[str, tuple[str, ...]] = {
    "docs/current_runtime": ("runtime", "architecture"),
    "docs/runtime": ("runtime",),
    "docs/GOVERNANCE": ("governance",),
    "docs/canonical": ("governance",),
    "docs/canon": ("governance",),
    "docs/PROOFS": ("testing",),
    "docs/testing": ("testing",),
    "docs/design": ("architecture",),
    "docs/reference/HUMAN_GUIDES": ("architecture",),
    "nova_backend/src/governor": ("governance",),
    "nova_backend/src/governance": ("governance",),
    "nova_backend/src/openclaw": ("openclaw", "runtime"),
    "nova_backend/src/memory": ("memory",),
    "nova_backend/src/working_context": ("memory",),
    "nova_backend/src/voice": ("voice",),
    "nova_backend/static": ("ux",),
    "Nova-Frontend-Dashboard": ("ux",),
    "nova_backend/tests": ("testing",),
}


@dataclass
class NoteRef:
    path: Path
    rel: Path
    title: str
    category: str
    kind: str = "doc"
    phase: str | None = None
    topics: set[str] = field(default_factory=set)
    summary: str = ""


def _tracked_repo_paths() -> list[Path]:
    try:
        raw = subprocess.check_output(["git", "ls-files", "-z"], cwd=REPO_ROOT)
    except (OSError, subprocess.CalledProcessError):
        return []
    paths: list[Path] = []
    for chunk in raw.split(b"\0"):
        if not chunk:
            continue
        rel = chunk.decode("utf-8", errors="surrogateescape")
        path = REPO_ROOT / rel
        if path.exists() and path.is_file():
            paths.append(path)
    return paths


def _root_note_files() -> tuple[Path, ...]:
    return tuple(
        path
        for path in (
            REPO_ROOT / "README.md",
            REPO_ROOT / "REPO_MAP.md",
            REPO_ROOT / "CONTRIBUTING.md",
            REPO_ROOT / "SECURITY.md",
        )
        if path.exists()
    )


def _runtime_code_queries() -> list[str]:
    src_root = REPO_ROOT / "nova_backend" / "src"
    if not src_root.exists():
        return []
    excluded = {"governor", "governance", "__pycache__"}
    return [
        f"path:nova_backend/src/{entry.name}"
        for entry in sorted(src_root.iterdir(), key=lambda item: item.name.lower())
        if entry.is_dir() and entry.name not in excluded
    ]


def _iter_source_files() -> Iterable[Path]:
    seen: set[Path] = set()
    tracked = _tracked_repo_paths()
    if tracked:
        for path in tracked:
            try:
                rel_parts = path.relative_to(REPO_ROOT).parts
            except ValueError:
                continue
            if any(part in SKIP_DIR_NAMES for part in rel_parts):
                continue
            if path in seen:
                continue
            seen.add(path)
            yield path
    for path in _root_note_files():
        if path in seen:
            continue
        seen.add(path)
        yield path
    if MOC_DIR.exists():
        for path in MOC_DIR.glob("*.md"):
            if path in seen:
                continue
            seen.add(path)
            yield path


def _extract_phase(rel: Path) -> str | None:
    for part in rel.parts:
        match = PHASE_DIR_RE.match(part)
        if match:
            return f"Phase {match.group(1)}"
    match = PHASE_FILE_RE.search(rel.stem)
    if match:
        return f"Phase {match.group(1)}"
    return None


def _extract_topics(rel: Path, head: str) -> set[str]:
    rel_text = rel.as_posix()
    rel_lower = rel_text.lower()
    topics: set[str] = set()

    for path_prefix, hinted_topics in TOPIC_PATH_HINTS.items():
        if rel_text.startswith(path_prefix):
            topics.update(hinted_topics)

    heading_match = TITLE_HEADING_RE.search(head)
    heading_text = heading_match.group(1).lower() if heading_match else ""
    summary_text = _extract_summary(head, "doc" if rel.suffix.lower() in NOTE_SUFFIXES else "code").lower()
    haystack = f"{rel_lower} {heading_text} {summary_text}"
    for topic, keywords in TOPIC_KEYWORDS.items():
        if any(keyword in haystack for keyword in keywords):
            topics.add(topic)
    return topics


def _classify(rel: Path, phase: str | None) -> tuple[str, str]:
    parts = rel.parts
    parts_lower = [part.lower() for part in parts]
    suffix = rel.suffix.lower()
    if suffix in NOTE_SUFFIXES:
        kind = "doc"
    elif suffix in ASSET_SUFFIXES:
        kind = "asset"
    else:
        kind = "code"

    if "archive" in parts_lower or any(part.startswith("archive(") for part in parts_lower):
        return "archive", kind
    if "proofs" in parts_lower:
        return "proofs", kind
    if parts_lower[:2] == ["nova_backend", "tests"] or parts_lower[:2] == ["docs", "testing"] or parts_lower[:1] == ["verification"]:
        return "tests", kind
    if parts_lower[:1] == ["automations"] or parts_lower[:1] == ["scripts"] or parts_lower[:1] == [".github"]:
        return "scripts", kind
    if parts_lower[:2] == ["docs", "tools"]:
        return "scripts", kind
    if parts_lower[:2] == ["nova_backend", "static"] or parts_lower[:1] == ["nova-frontend-dashboard"]:
        return "frontend", kind
    if parts_lower[:1] == ["novalis-governance"]:
        return "governance", kind
    if parts_lower[:2] == ["nova_backend", "src"]:
        if len(parts_lower) > 2 and parts_lower[2] in {"governor", "governance"}:
            return "governance", kind
        return "runtime", kind
    if parts_lower[:1] == ["nova_workspace"]:
        return "runtime", kind
    if parts_lower[:1] == ["pull_requests"]:
        return "reference", kind
    if parts_lower[:1] == ["docs"]:
        if len(parts_lower) > 1 and parts_lower[1] in {"governance", "canonical", "canon"}:
            return "governance", kind
        if len(parts_lower) > 1 and parts_lower[1] in {"current_runtime", "runtime"}:
            return "runtime", kind
        if len(parts_lower) > 1 and parts_lower[1] == "reference":
            return "reference", kind
        if len(parts_lower) > 1 and parts_lower[1] == "proofs":
            return "proofs", kind
        if len(parts_lower) > 1 and parts_lower[1] == "design":
            if phase:
                return "phase", kind
            return "design", kind
        if phase:
            return "phase", kind
        return "reference", kind
    if phase:
        return "phase", kind
    if len(parts_lower) == 1 and suffix in NOTE_SUFFIXES:
        return "reference", kind
    return "reference", kind


def _extract_title(path: Path, head: str, kind: str) -> str:
    if kind == "doc":
        match = TITLE_HEADING_RE.search(head)
        if match:
            return match.group(1).strip()
    if kind == "asset":
        return path.name
    return path.stem.strip() or path.stem


def _extract_summary(head: str, kind: str, max_len: int = 140) -> str:
    if kind == "asset":
        return ""
    if kind == "code":
        for raw_line in head.splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#!"):
                continue
            line = line.lstrip("#").lstrip("/").lstrip("*").strip(" \"'`")
            lowered = line.lower()
            if lowered.startswith("from __future__ import"):
                continue
            if lowered.startswith("from ") or lowered.startswith("import "):
                continue
            if lowered in {"from __future__ import annotations", "__init__.py"}:
                continue
            if "/" in line and (line.endswith(".py") or line.endswith(".js") or line.endswith(".html")):
                continue
            if len(line) >= 4:
                return line[:max_len].rstrip() + ("..." if len(line) > max_len else "")
        return ""

    in_frontmatter = False
    for raw_line in head.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line == "---":
            in_frontmatter = not in_frontmatter
            continue
        if in_frontmatter or line.startswith(("#", "<!--", "```", ">")):
            continue
        line = re.sub(r"[*_`]+", "", line)
        line = re.sub(r"\s+", " ", line).strip()
        if len(line) >= 4:
            return line[:max_len].rstrip() + ("..." if len(line) > max_len else "")
    return ""


def scan_notes() -> list[NoteRef]:
    notes: list[NoteRef] = []
    for path in _iter_source_files():
        rel = path.relative_to(REPO_ROOT)
        try:
            head = path.read_text(encoding="utf-8", errors="replace")[:2400]
        except OSError:
            head = ""
        phase = _extract_phase(rel)
        category, kind = _classify(rel, phase)
        notes.append(
            NoteRef(
                path=path,
                rel=rel,
                title=_extract_title(path, head, kind),
                category=category,
                kind=kind,
                phase=phase,
                topics=_extract_topics(rel, head),
                summary=_extract_summary(head, kind),
            )
        )
    notes.sort(key=lambda note: note.rel.as_posix().lower())
    _polish_package_titles(notes)
    _disambiguate_titles(notes)
    return notes


def _polish_package_titles(notes: list[NoteRef]) -> None:
    """Give every `__init__.py` a human label instead of the stem "__init__".

    Before: lists showed `__init__ - src/audit` (disambiguation suffix).
    After: `src/audit` — the label is the dotted package path, which is what a
    reader actually wants to see when scanning a file list.
    """
    for note in notes:
        if note.path.name != "__init__.py":
            continue
        parts = list(note.rel.parent.parts)
        if parts[:1] == ["nova_backend"]:
            parts = parts[1:]
        if parts:
            note.title = "/".join(parts)


def _disambiguate_titles(notes: list[NoteRef]) -> None:
    by_title: dict[str, list[NoteRef]] = {}
    for note in notes:
        by_title.setdefault(note.title.lower(), []).append(note)
    for bucket in by_title.values():
        if len(bucket) < 2:
            continue
        for note in bucket:
            parent = note.rel.parent.as_posix() or "."
            hint = "/".join(parent.split("/")[-2:]) if parent != "." else parent
            note.title = f"{note.title} - {hint}"


def _wikilink(note: NoteRef) -> str:
    rel = note.rel.as_posix()
    if note.kind == "doc" and rel.lower().endswith(".md"):
        rel = rel[:-3]
    return f"[[{rel}|{note.title}]]"


def _link_target_exists(target: str) -> bool:
    return (REPO_ROOT / target).exists() or (REPO_ROOT / f"{target}.md").exists()


def _append_if_exists(lines: list[str], label: str, target: str) -> None:
    if _link_target_exists(target):
        lines.append(f"- [[{target}|{label}]]")


def _write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def _frontmatter(tags: list[str]) -> list[str]:
    return ["---", "tags:", *[f"  - {tag}" for tag in tags], "---"]


def write_home(notes: list[NoteRef]) -> None:
    doc_counts = {category: 0 for category in CATEGORY_ORDER}
    code_counts = {category: 0 for category in CATEGORY_ORDER}
    for note in notes:
        if note.kind == "doc":
            doc_counts[note.category] = doc_counts.get(note.category, 0) + 1
        else:
            code_counts[note.category] = code_counts.get(note.category, 0) + 1

    lines = [
        *_frontmatter(["moc", "nova", "home"]),
        GENERATED_MARKER,
        "",
        "# Nova Vault Home",
        "",
        "You're looking at the Nova repository opened as an Obsidian vault.",
        "Docs and code sit in the same graph; files sharing a concern share a color.",
        "Sources are never edited — this overlay just builds navigation on top.",
        "",
        "## New here? Start here",
        "",
        "- [[_MOCs/USER_PATHS|Guided entry points — the fewest clicks to what you need]]",
        "",
        "## Browse the repo",
        "",
        "- [[_MOCs/REPO_BY_FOLDER|Walk the tree — same layout as GitHub]]",
        "- [[_MOCs/RECENT|See what changed most recently]]",
        "- [[_MOCs/BY_PHASE|Follow the build phase by phase]]",
        "- [[_MOCs/BY_TOPIC|Browse by cross-cutting theme]]",
        "- [[_MOCs/BY_TYPE|Group everything by category (strongest connected view)]]",
        "",
        "## Read the code",
        "",
        "- [[_MOCs/CODE_BY_LAYER|Source by runtime layer]]",
        "- [[_MOCs/CODE_MODULES|Dive into a module — files, imports, importers, tests]]",
        "- [[_MOCs/CODE_IMPORTS|Follow imports between modules]]",
        "- [[_MOCs/TEST_MAP|Find the test for a source file]]",
        "",
        "## How to read the graph",
        "",
        "- Open the graph view (`Ctrl+G`). Same-color dots are connected by concern, not just folder.",
        "- Hover any file in the graph to preview; click to open.",
        "- Color legend:",
    ]
    for category in CATEGORY_ORDER:
        lines.append(f"    - {CATEGORY_LABELS[category]}")
    lines.extend(
        [
            "",
            "## By the numbers",
            "",
            "| Category | Docs | Code |",
            "|---|---:|---:|",
        ]
    )
    for category in CATEGORY_ORDER:
        lines.append(
            f"| {CATEGORY_LABELS[category]} | {doc_counts[category]} | {code_counts[category]} |"
        )
    lines.extend(
        [
            "",
            f"_Indexed {sum(doc_counts.values())} docs and {sum(code_counts.values())} non-doc files._",
            "",
        ]
    )
    _write(MOC_DIR / "HOME.md", "\n".join(lines))


def write_user_paths(notes: list[NoteRef]) -> None:
    """Section-oriented entry points.

    Each heading is a question a real user would ask; the line below says when
    to use that section. Outcome-first phrasing, no internal jargon in headers.
    """
    sections: list[tuple[str, str, list[tuple[str, str]]]] = [
        (
            "I'm new — what is Nova?",
            "Start here for a plain-language picture of the system and how it behaves.",
            [
                ("README", "README"),
                ("Human Guides README", "docs/reference/HUMAN_GUIDES/README"),
                ("System process and explainability guide",
                 "docs/reference/HUMAN_GUIDES/32_NOVA_SYSTEM_PROCESS_AND_EXPLAINABILITY_GUIDE"),
                ("Current runtime state", "docs/current_runtime/CURRENT_RUNTIME_STATE"),
            ],
        ),
        (
            "What is actually running right now?",
            "Live-truth snapshots — what the runtime auditor sees today.",
            [
                ("Current runtime state", "docs/current_runtime/CURRENT_RUNTIME_STATE"),
                ("Runtime capability reference", "docs/current_runtime/RUNTIME_CAPABILITY_REFERENCE"),
                ("Runtime fingerprint", "docs/current_runtime/RUNTIME_FINGERPRINT"),
            ],
        ),
        (
            "What's happening on the product and UX side?",
            "Recent UX direction, current-state report, and the friction roadmap.",
            [
                ("Current state", "docs/reference/HUMAN_GUIDES/07_CURRENT_STATE"),
                ("Frontend and UI guide", "docs/reference/HUMAN_GUIDES/14_FRONTEND_AND_UI_GUIDE"),
                ("UX friction remediation roadmap",
                 "docs/design/Phase 4.5/NOVA_UX_FRICTION_REMEDIATION_ROADMAP_2026-04-14"),
            ],
        ),
        (
            "How does OpenClaw and the operator work?",
            "Setup, the integration standard, and the local code operator roadmap.",
            [
                ("OpenClaw setup and runtime guide",
                 "docs/reference/HUMAN_GUIDES/28_OPENCLAW_SETUP_AND_RUNTIME_GUIDE_2026-03-27"),
                ("Local code operator and project analysis",
                 "docs/reference/HUMAN_GUIDES/31_LOCAL_CODE_OPERATOR_AND_PROJECT_ANALYSIS"),
                ("Nova-OpenClaw integration standard",
                 "docs/design/Phase 8/NOVA_OPENCLAW_INTEGRATION_STANDARD_2026-04-14"),
                ("Local code operator roadmap",
                 "docs/design/Phase 8/NOVA_LOCAL_CODE_OPERATOR_ROADMAP_2026-04-13"),
            ],
        ),
        (
            "I want to read the code",
            "Several lenses — whole-tree browse, per-module detail, import graph, test ↔ source.",
            [
                ("Repo map", "REPO_MAP"),
                ("Source by runtime layer", "_MOCs/CODE_BY_LAYER"),
                ("Dive into a module", "_MOCs/CODE_MODULES"),
                ("Follow imports between modules", "_MOCs/CODE_IMPORTS"),
                ("Find the test for a source file", "_MOCs/TEST_MAP"),
                ("Codebase tour", "docs/reference/HUMAN_GUIDES/12_CODEBASE_TOUR"),
            ],
        ),
        (
            "Is this thing trustworthy?",
            "Governance matrix, bypass surfaces, and the canonical contract map.",
            [
                ("Governance matrix", "docs/current_runtime/GOVERNANCE_MATRIX"),
                ("Bypass surfaces", "docs/current_runtime/BYPASS_SURFACES"),
                ("Canonical document map", "docs/canonical/CANONICAL_DOCUMENT_MAP"),
            ],
        ),
    ]

    lines = [
        *_frontmatter(["moc", "nova", "user-paths"]),
        GENERATED_MARKER, "",
        "# Guided paths", "",
        "Pick the question that sounds like yours. Each section is a hand-picked",
        "reading list — a few links, not the whole tree. For the full repo, go to",
        "[[_MOCs/HOME|Vault home]] or [[_MOCs/REPO_BY_FOLDER|Repo by folder]].", "",
    ]
    for heading, intro, items in sections:
        lines.append(f"## {heading}")
        lines.append("")
        lines.append(f"_{intro}_")
        lines.append("")
        section_lines: list[str] = []
        for label, target in items:
            if _link_target_exists(target):
                section_lines.append(f"- [[{target}|{label}]]")
        if section_lines:
            lines.extend(section_lines)
        else:
            lines.append("_No linked entries resolved for this section._")
        lines.append("")

    lines.append("## Tips for using this vault")
    lines.append("")
    lines.append("- Open the graph (`Ctrl+G`) — same-color dots are connected by concern.")
    lines.append("- [[_MOCs/BY_TYPE|By category]] is the strongest connected view.")
    lines.append("- [[_MOCs/BY_TOPIC|By topic]] is lighter, cross-cutting guidance.")
    lines.append("- [[_MOCs/RECENT|Recently updated]] shows what changed most recently across docs and code.")
    lines.append("")
    _write(MOC_DIR / "USER_PATHS.md", "\n".join(lines))


def write_repo_by_folder(notes: list[NoteRef]) -> None:
    buckets: dict[str, list[NoteRef]] = {}
    for note in notes:
        top = note.rel.parts[0] if note.rel.parts else "(root)"
        buckets.setdefault(top, []).append(note)

    lines = [
        *_frontmatter(["moc", "nova", "repo"]),
        GENERATED_MARKER,
        "",
        "# Walk the repo by folder",
        "",
        "Every tracked file in the repository, grouped by top-level folder — the",
        "same layout you'd see on GitHub. Use this when you want the whole map.",
        "",
    ]
    for folder in sorted(buckets, key=str.lower):
        bucket = sorted(buckets[folder], key=lambda item: item.rel.as_posix().lower())
        lines.extend([f"## {folder} ({len(bucket)})", ""])
        for note in bucket:
            lines.append(f"- [{note.kind}] {_wikilink(note)}")
            if note.summary:
                lines.append(f"  summary: {note.summary}")
        lines.append("")
    _write(MOC_DIR / "REPO_BY_FOLDER.md", "\n".join(lines))


def write_by_phase(notes: list[NoteRef]) -> None:
    by_phase: dict[str, list[NoteRef]] = {}
    for note in notes:
        if note.phase:
            by_phase.setdefault(note.phase, []).append(note)

    def phase_sort_key(label: str) -> tuple[float, str]:
        match = re.search(r"([0-9]+(?:\.[0-9]+)?)", label)
        return (float(match.group(1)) if match else 999.0, label)

    lines = [
        *_frontmatter(["moc", "nova", "by-phase"]),
        GENERATED_MARKER,
        "",
        "# Follow the build phase by phase",
        "",
        "Docs and code grouped by project phase, inferred from folder and file",
        "names. Use this to see what shipped (or is planned) for each phase.",
        "",
    ]
    for phase in sorted(by_phase, key=phase_sort_key):
        lines.extend([f"## {phase}", ""])
        for note in sorted(by_phase[phase], key=lambda item: (item.kind, item.title.lower())):
            lines.append(f"- [{note.kind}] {_wikilink(note)}")
        lines.append("")
    _write(MOC_DIR / "BY_PHASE.md", "\n".join(lines))


def write_by_topic(notes: list[NoteRef]) -> None:
    by_topic: dict[str, list[NoteRef]] = {topic: [] for topic in TOPIC_KEYWORDS}
    for note in notes:
        for topic in note.topics:
            by_topic.setdefault(topic, []).append(note)

    lines = [
        *_frontmatter(["moc", "nova", "by-topic"]),
        GENERATED_MARKER,
        "",
        "# Browse by theme",
        "",
        "A lighter, cross-cutting view than categories — a file can appear under",
        "multiple themes when its path or contents match several concerns.",
        "Best used after [[_MOCs/USER_PATHS|Guided paths]] or [[_MOCs/BY_TYPE|By category]].",
        "",
    ]
    for topic in TOPIC_KEYWORDS:
        bucket = by_topic.get(topic, [])
        if not bucket:
            continue
        lines.extend([f"## {topic} ({len(bucket)})", ""])
        for note in sorted(bucket, key=lambda item: (item.kind, item.title.lower())):
            lines.append(f"- [{note.kind}] {_wikilink(note)}")
        lines.append("")
    _write(MOC_DIR / "BY_TOPIC.md", "\n".join(lines))


def write_by_type(notes: list[NoteRef]) -> None:
    buckets: dict[str, list[NoteRef]] = {category: [] for category in CATEGORY_ORDER}
    for note in notes:
        buckets.setdefault(note.category, []).append(note)

    lines = [
        *_frontmatter(["moc", "nova", "by-category"]),
        GENERATED_MARKER,
        "",
        "# Group everything by category",
        "",
        "The strongest connected view: docs and code in the same concern area",
        "share the same graph color group. Use this when you want to see how a",
        "concern is reflected across docs, code and tests.",
        "",
    ]
    for category in CATEGORY_ORDER:
        bucket = buckets.get(category, [])
        if not bucket:
            continue
        doc_count = sum(1 for note in bucket if note.kind == "doc")
        code_count = len(bucket) - doc_count
        lines.extend(
            [
                f"## {CATEGORY_LABELS[category]} ({doc_count} docs, {code_count} code)",
                "",
            ]
        )
        for note in sorted(bucket, key=lambda item: (item.kind, item.rel.as_posix().lower())):
            phase_suffix = f" - {note.phase}" if note.phase else ""
            lines.append(f"- [{note.kind}] {_wikilink(note)}{phase_suffix}")
            if note.summary:
                lines.append(f"  summary: {note.summary}")
        lines.append("")
    _write(MOC_DIR / "BY_TYPE.md", "\n".join(lines))


def write_code_by_layer(notes: list[NoteRef]) -> None:
    layers: list[tuple[str, callable]] = [
        ("Backend runtime", lambda note: note.kind != "doc" and note.rel.parts[:2] == ("nova_backend", "src")),
        ("Tests and verification", lambda note: note.kind != "doc" and (note.rel.parts[:2] == ("nova_backend", "tests") or note.rel.parts[:1] == ("verification",))),
        ("Frontend", lambda note: note.kind != "doc" and note.rel.parts[:2] == ("nova_backend", "static")),
        (
            "Frontend mirror",
            lambda note: note.kind != "doc" and note.rel.parts[:1] == ("Nova-Frontend-Dashboard",),
        ),
        ("Scripts and automations", lambda note: note.kind != "doc" and (note.rel.parts[:1] == ("scripts",) or note.rel.parts[:1] == ("automations",) or note.rel.parts[:1] == (".github",))),
        ("Governance companion repo", lambda note: note.rel.parts[:1] == ("NovaLIS-Governance",)),
        (
            "Workspace and repo support",
            lambda note: note.kind != "doc"
            and (
                note.rel.parts[:1] in {("nova_workspace",), ("pull_requests",)}
                or len(note.rel.parts) == 1
            ),
        ),
    ]

    lines = [
        *_frontmatter(["moc", "nova", "code"]),
        GENERATED_MARKER,
        "",
        "# Read source by runtime layer",
        "",
        "Every code file grouped by the major repo layers — backend runtime,",
        "tests, frontend, scripts, governance companion, workspace support.",
        "Use this to orient yourself before diving into a specific module.",
        "",
    ]
    for label, predicate in layers:
        bucket = [note for note in notes if predicate(note)]
        if not bucket:
            continue
        lines.extend([f"## {label} ({len(bucket)})", ""])
        for note in sorted(bucket, key=lambda item: item.rel.as_posix().lower()):
            lines.append(f"- {_wikilink(note)}")
            if note.summary:
                lines.append(f"  summary: {note.summary}")
        lines.append("")
    _write(MOC_DIR / "CODE_BY_LAYER.md", "\n".join(lines))


# ---------- Python import + test pairing (drives CODE_MODULES / CODE_IMPORTS) ----------

SRC_ROOT_REL = ("nova_backend", "src")
TESTS_ROOT_REL = ("nova_backend", "tests")

IMPORT_RE = re.compile(
    r"^(?P<indent>[ \t]*)(?:from\s+(?P<frm>[.\w]+)\s+import|import\s+(?P<mod>[.\w]+))",
    re.MULTILINE,
)


def _is_python_src(note: NoteRef) -> bool:
    return (
        note.kind == "code"
        and note.path.suffix.lower() == ".py"
        and note.rel.parts[:2] == SRC_ROOT_REL
    )


def _is_python_test(note: NoteRef) -> bool:
    return (
        note.kind == "code"
        and note.path.suffix.lower() == ".py"
        and note.rel.parts[:2] == TESTS_ROOT_REL
    )


def _module_path_for(src_rel: Path) -> str:
    """Return the dotted module path for a nova_backend/src/*.py note.

    Nova adds `nova_backend/` to sys.path, so real imports use the `src.foo.bar`
    form. We strip the `nova_backend.` prefix so the module paths we emit match
    the import text the parser finds.
    """
    parts = list(src_rel.parts)
    if parts[:2] == list(SRC_ROOT_REL):  # ("nova_backend", "src") -> drop the first
        parts = parts[1:]
    if parts[-1] == "__init__.py":
        parts = parts[:-1]
    elif parts[-1].endswith(".py"):
        parts[-1] = parts[-1][:-3]
    return ".".join(parts)  # e.g. "src.audit.runtime_auditor"


def _resolve_relative_import(src_rel: Path, frm: str) -> str | None:
    """Turn a `from .X.Y import ...` into its absolute dotted module path.

    The result uses the same `src.foo.bar` form Nova actually imports against.
    """
    if not frm.startswith("."):
        return frm
    dots = len(frm) - len(frm.lstrip("."))
    tail = frm[dots:]
    parts = list(src_rel.parts[:-1])  # drop filename
    if parts[:2] == list(SRC_ROOT_REL):
        parts = parts[1:]
    if dots > len(parts):
        return None
    base = parts[: len(parts) - (dots - 1)]
    if tail:
        base.extend(tail.split("."))
    return ".".join(base) if base else None


def _build_import_index(notes: list[NoteRef]) -> tuple[dict[str, NoteRef], dict[Path, set[str]]]:
    """Return (module_path -> owning src note, src_rel -> imported_module_paths)."""
    by_module: dict[str, NoteRef] = {}
    for note in notes:
        if _is_python_src(note):
            by_module[_module_path_for(note.rel)] = note

    imports_by_file: dict[Path, set[str]] = {}
    # Longest-prefix-first so `src.governor.foo.bar` matches `src.governor.foo.bar`
    # before shorter ancestor prefixes like `src.governor` or bare `src`.
    known_prefixes = sorted(by_module.keys(), key=len, reverse=True)
    for note in notes:
        if note.path.suffix.lower() != ".py":
            continue
        try:
            text = note.path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        targets: set[str] = set()
        for match in IMPORT_RE.finditer(text):
            raw = match.group("frm") or match.group("mod") or ""
            if not raw:
                continue
            resolved = (
                _resolve_relative_import(note.rel, raw) if raw.startswith(".") else raw
            )
            if not resolved or resolved == "src":
                # "src" alone is the package root and would match every import.
                continue
            for prefix in known_prefixes:
                if prefix == "src":
                    continue
                if resolved == prefix or resolved.startswith(prefix + "."):
                    targets.add(prefix)
                    break
        if targets:
            imports_by_file[note.rel] = targets
    return by_module, imports_by_file


def _pair_tests_to_sources(
    notes: list[NoteRef], by_module: dict[str, NoteRef]
) -> dict[Path, list[NoteRef]]:
    """Map each test file to any source files it most likely covers by name.

    Skips `__init__.py` on both sides. The init stem matches every module's
    init, which produced a useless map where every test appeared to cover
    every package root. Real tests have their own filenames.
    """
    src_by_stem: dict[str, list[NoteRef]] = {}
    for note in by_module.values():
        if note.path.name == "__init__.py":
            continue
        src_by_stem.setdefault(note.path.stem.lower(), []).append(note)

    pairs: dict[Path, list[NoteRef]] = {}
    for note in notes:
        if not _is_python_test(note):
            continue
        if note.path.name == "__init__.py":
            continue
        stem = note.path.stem.lower()
        if not stem.startswith("test_"):
            # Conftest, helpers, fixtures etc. aren't themselves tests of a
            # specific source file — skip so the map stays focused.
            continue
        base = stem[5:]
        matches = src_by_stem.get(base, [])
        if matches:
            pairs[note.rel] = matches
    return pairs


def write_code_modules(
    notes: list[NoteRef],
    by_module: dict[str, NoteRef],
    imports_by_file: dict[Path, set[str]],
    test_pairs: dict[Path, list[NoteRef]],
) -> None:
    """One rich MOC section per top-level nova_backend/src/<module>/."""
    # Group src notes by their top-level module directory (or bare file).
    by_top: dict[str, list[NoteRef]] = {}
    for note in notes:
        if not _is_python_src(note):
            continue
        parts = note.rel.parts
        # parts[:2] == nova_backend/src; [2] is module dir or file.
        if len(parts) < 3:
            continue
        top = parts[2]
        # The root `nova_backend/src/__init__.py` isn't its own module — it's
        # the package root marker. Skip it so we don't invent a bogus
        # "__init__" section that lists only itself.
        if top == "__init__.py":
            continue
        if top.endswith(".py"):
            top = top[:-3]  # bare files like base_skill.py become their own "module"
        by_top.setdefault(top, []).append(note)

    # Reverse import edges: for each source note, who imports its module.
    reverse: dict[Path, set[Path]] = {}
    for importer_rel, targets in imports_by_file.items():
        for module_path in targets:
            target_note = by_module.get(module_path)
            if not target_note:
                continue
            # Attribute the reverse edge to the top-level of the imported module.
            reverse.setdefault(target_note.rel, set()).add(importer_rel)

    # Test pairs indexed by source rel.
    tests_by_src: dict[Path, list[NoteRef]] = {}
    for test_rel, src_notes in test_pairs.items():
        test_note = next((n for n in notes if n.rel == test_rel), None)
        if not test_note:
            continue
        for src_note in src_notes:
            tests_by_src.setdefault(src_note.rel, []).append(test_note)

    lines = [
        *_frontmatter(["moc", "nova", "code", "modules"]),
        GENERATED_MARKER,
        "",
        "# Dive into a module",
        "",
        "One section per top-level module under `nova_backend/src/`. Each section",
        "shows the module's files, what it imports, what imports it, and the",
        "tests that pair by filename — so you can see the whole blast radius.",
        "",
    ]

    # Alphabetical module ordering with __init__.py / base first for readability.
    for module_name in sorted(by_top.keys(), key=lambda s: s.lower()):
        module_notes = sorted(by_top[module_name], key=lambda n: n.rel.as_posix().lower())
        lines.append(f"## `{module_name}` ({len(module_notes)} files)")
        lines.append("")

        # Module summary: prefer __init__.py docstring if present.
        init_note = next((n for n in module_notes if n.path.name == "__init__.py"), None)
        if init_note and init_note.summary:
            lines.append(f"_{init_note.summary}_")
            lines.append("")

        # Files (capped — keep MOC scan-able).
        lines.append("### Files")
        lines.append("")
        for note in module_notes[:25]:
            lines.append(f"- {_wikilink(note)}")
            if note.summary and note.path.name != "__init__.py":
                lines.append(f"    - {note.summary}")
        if len(module_notes) > 25:
            lines.append(f"- _…and {len(module_notes) - 25} more_")
        lines.append("")

        # Imports out — which other internal modules this module pulls in.
        out_modules: set[str] = set()
        for note in module_notes:
            out_modules.update(imports_by_file.get(note.rel, set()))
        # Drop self-imports so the list is signal. Module paths use the `src.X`
        # form Nova imports against, matching _module_path_for.
        self_module_prefix = f"src.{module_name}"
        out_modules = {
            m for m in out_modules
            if m != self_module_prefix and not m.startswith(self_module_prefix + ".")
        }
        if out_modules:
            lines.append("### Imports from")
            lines.append("")
            # Wikilinks already embed the path, so skip the `(src.foo.bar)`
            # suffix that used to clutter every line.
            for module_path in sorted(out_modules):
                target = by_module.get(module_path)
                if target:
                    lines.append(f"- {_wikilink(target)}")
            lines.append("")

        # Imports in — which other internal modules reach into this one.
        in_files: set[Path] = set()
        for note in module_notes:
            in_files.update(reverse.get(note.rel, set()))
        in_files = {
            rel for rel in in_files
            if not rel.as_posix().startswith(
                f"{SRC_ROOT_REL[0]}/{SRC_ROOT_REL[1]}/{module_name}/"
            )
        }
        if in_files:
            lines.append("### Imported by")
            lines.append("")
            importer_notes = [
                n for n in notes if n.rel in in_files
            ]
            for importer in sorted(importer_notes, key=lambda n: n.rel.as_posix().lower())[:15]:
                lines.append(f"- {_wikilink(importer)}")
            if len(importer_notes) > 15:
                lines.append(f"- _…and {len(importer_notes) - 15} more_")
            lines.append("")

        # Tests that cover files in this module by filename.
        module_tests: list[NoteRef] = []
        for note in module_notes:
            module_tests.extend(tests_by_src.get(note.rel, []))
        # Deduplicate while preserving order.
        seen_test_rels: set[Path] = set()
        unique_tests = [
            t for t in module_tests if not (t.rel in seen_test_rels or seen_test_rels.add(t.rel))
        ]
        if unique_tests:
            lines.append("### Tests")
            lines.append("")
            for test in sorted(unique_tests, key=lambda n: n.rel.as_posix().lower()):
                lines.append(f"- {_wikilink(test)}")
            lines.append("")

    _write(MOC_DIR / "CODE_MODULES.md", "\n".join(lines))


def write_code_imports(
    notes: list[NoteRef],
    by_module: dict[str, NoteRef],
    imports_by_file: dict[Path, set[str]],
) -> None:
    """Flat list of inter-module import edges as wikilinks so the graph connects."""
    # Collapse file-level edges up to module-level for a clean graph.
    module_edges: dict[str, set[str]] = {}
    for importer_rel, targets in imports_by_file.items():
        if importer_rel.parts[:2] != SRC_ROOT_REL or len(importer_rel.parts) < 3:
            continue
        importer_top = importer_rel.parts[2]
        if importer_top.endswith(".py"):
            importer_top = importer_top[:-3]
        for module_path in targets:
            tail = module_path.split(".")
            # module_path form is "src.<top>[.<...>]" (stripped prefix).
            if len(tail) < 2 or tail[0] != "src":
                continue
            target_top = tail[1]
            if target_top == importer_top:
                continue
            module_edges.setdefault(importer_top, set()).add(target_top)

    lines = [
        *_frontmatter(["moc", "nova", "code", "imports"]),
        GENERATED_MARKER,
        "",
        "# Follow imports between modules",
        "",
        "Each top-level `nova_backend/src/` module and the other modules it pulls",
        "in. Every bullet is a clickable wikilink, so the graph view shows real",
        "code connectivity — not just shared folders.",
        "",
    ]
    for importer in sorted(module_edges.keys(), key=lambda s: s.lower()):
        targets = sorted(module_edges[importer])
        lines.append(f"## `{importer}`")
        lines.append("")
        lines.append("Imports from:")
        lines.append("")
        for target in targets:
            # Prefer the module's __init__.py if present; otherwise pick any
            # file under that top-level module so the edge is still clickable.
            # Module keys use the `src.X` form (we stripped nova_backend.
            # earlier), so the fallback prefix must match. After the
            # __init__ title polish the wikilink already reads as e.g.
            # "src/audit", so no suffix needed to identify the module.
            target_init = by_module.get(f"src.{target}")
            if target_init:
                lines.append(f"- {_wikilink(target_init)}")
                continue
            any_note = next(
                (
                    by_module[m]
                    for m in sorted(by_module.keys())
                    if m.startswith(f"src.{target}.")
                ),
                None,
            )
            if any_note:
                lines.append(f"- {_wikilink(any_note)} (in `{target}`)")
            else:
                lines.append(f"- `{target}`")
        lines.append("")
    _write(MOC_DIR / "CODE_IMPORTS.md", "\n".join(lines))


def write_test_map(
    notes: list[NoteRef],
    test_pairs: dict[Path, list[NoteRef]],
) -> None:
    """Two-column view of test files and the source files they most likely cover.

    Always emitted so the link from HOME/USER_PATHS resolves even when a test
    run (or a trimmed vault) produces no pairs — the empty-state body keeps the
    graph stable instead of 404-ing on an expected MOC.
    """
    notes_by_rel = {n.rel: n for n in notes}
    lines = [
        *_frontmatter(["moc", "nova", "tests"]),
        GENERATED_MARKER,
        "",
        "# Find the test for a source file",
        "",
        "Every `nova_backend/tests/test_<name>.py` paired with the source file",
        "whose filename stem matches. Useful for jumping between a test and the",
        "code it exercises. `__init__.py`, conftest and helper modules are",
        "intentionally skipped so the map stays focused on real test ↔ source links.",
        "",
        f"Paired tests: {len(test_pairs)}",
        "",
    ]

    if not test_pairs:
        lines.extend([
            "_No test ↔ source pairs resolved in this vault._",
            "",
            "Add a `nova_backend/tests/test_<name>.py` that mirrors a source file",
            "name (e.g. `test_runtime_auditor.py` pairs with",
            "`nova_backend/src/audit/runtime_auditor.py`) and re-run the overlay.",
            "",
        ])
    else:
        for test_rel in sorted(test_pairs.keys(), key=lambda p: p.as_posix().lower()):
            test_note = notes_by_rel.get(test_rel)
            if not test_note:
                continue
            src_notes = test_pairs[test_rel]
            lines.append(f"- {_wikilink(test_note)}")
            for src_note in sorted(src_notes, key=lambda n: n.rel.as_posix().lower()):
                lines.append(f"    - tests → {_wikilink(src_note)}")
        lines.append("")

    _write(MOC_DIR / "TEST_MAP.md", "\n".join(lines))


def write_recent(notes: list[NoteRef], limit: int = 80) -> None:
    newest = sorted(notes, key=lambda note: note.path.stat().st_mtime, reverse=True)[:limit]
    lines = [
        *_frontmatter(["moc", "nova", "recent"]),
        GENERATED_MARKER,
        "",
        f"# What changed most recently (top {limit})",
        "",
        "Docs and code ordered by filesystem modification time, newest first.",
        "Use this to catch up on what's been touched lately.",
        "",
    ]
    for note in newest:
        stamp = datetime.fromtimestamp(note.path.stat().st_mtime).strftime("%Y-%m-%d")
        lines.append(f"- `{stamp}` [{note.kind}] {_wikilink(note)}")
    lines.append("")
    _write(MOC_DIR / "RECENT.md", "\n".join(lines))


def _hex_to_rgb_int(hex_color: str) -> int:
    clean = hex_color.lstrip("#")
    return (int(clean[0:2], 16) << 16) | (int(clean[2:4], 16) << 8) | int(clean[4:6], 16)


def write_obsidian_config() -> None:
    VAULT_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    app_config = {
        "useMarkdownLinks": False,
        "newFileLocation": "folder",
        "newFileFolderPath": "_MOCs",
        "attachmentFolderPath": "_attachments",
        "alwaysUpdateLinks": True,
        "showLineNumber": True,
        "readableLineLength": True,
    }
    (VAULT_CONFIG_DIR / "app.json").write_text(json.dumps(app_config, indent=2), encoding="utf-8")

    appearance = {
        "baseFontSize": 16,
        "theme": "obsidian",
        "cssTheme": "",
        "accentColor": "#4F8AD8",
    }
    (VAULT_CONFIG_DIR / "appearance.json").write_text(json.dumps(appearance, indent=2), encoding="utf-8")

    core_plugins = [
        "file-explorer",
        "global-search",
        "graph",
        "backlink",
        "outgoing-link",
        "tag-pane",
        "starred",
        "outline",
        "word-count",
        "file-recovery",
    ]
    (VAULT_CONFIG_DIR / "core-plugins.json").write_text(
        json.dumps(core_plugins, indent=2),
        encoding="utf-8",
    )

    runtime_queries = list(dict.fromkeys(CATEGORY_QUERIES["runtime"] + _runtime_code_queries()))
    query_overrides = {"runtime": runtime_queries}

    color_groups = []
    for category in CATEGORY_ORDER:
        color_groups.append(
            {
                "query": " OR ".join(query_overrides.get(category, CATEGORY_QUERIES[category])),
                "color": {"a": 1, "rgb": _hex_to_rgb_int(CATEGORY_COLORS[category])},
            }
        )

    graph = {
        "collapse-filter": False,
        "search": "",
        "showTags": True,
        "showAttachments": False,
        "hideUnresolved": True,
        "showOrphans": True,
        "collapse-color-groups": False,
        "colorGroups": color_groups,
        "collapse-display": False,
        "showArrow": True,
        "textFadeMultiplier": 0,
        "nodeSizeMultiplier": 1.05,
        "lineSizeMultiplier": 1.0,
        "collapse-forces": False,
        "centerStrength": 0.5,
        "repelStrength": 10.0,
        "linkStrength": 1.0,
        "linkDistance": 250,
    }
    (VAULT_CONFIG_DIR / "graph.json").write_text(json.dumps(graph, indent=2), encoding="utf-8")

    # Star order = reading order a new user should try first.
    # Guided paths and Home come before any internal browsing MOC.
    starred = {
        "items": [
            {"type": "file", "title": "Guided paths (start here)", "path": "_MOCs/USER_PATHS.md"},
            {"type": "file", "title": "Vault home", "path": "_MOCs/HOME.md"},
            {"type": "file", "title": "Dive into a module", "path": "_MOCs/CODE_MODULES.md"},
            {"type": "file", "title": "Follow imports between modules", "path": "_MOCs/CODE_IMPORTS.md"},
            {"type": "file", "title": "Find the test for a source file", "path": "_MOCs/TEST_MAP.md"},
            {"type": "file", "title": "Source by runtime layer", "path": "_MOCs/CODE_BY_LAYER.md"},
            {"type": "file", "title": "Group by category", "path": "_MOCs/BY_TYPE.md"},
            {"type": "file", "title": "Browse by theme", "path": "_MOCs/BY_TOPIC.md"},
            {"type": "file", "title": "Follow by phase", "path": "_MOCs/BY_PHASE.md"},
            {"type": "file", "title": "Walk the repo by folder", "path": "_MOCs/REPO_BY_FOLDER.md"},
            {"type": "file", "title": "What changed recently", "path": "_MOCs/RECENT.md"},
        ]
    }
    (VAULT_CONFIG_DIR / "starred.json").write_text(json.dumps(starred, indent=2), encoding="utf-8")


def main() -> int:
    if not REPO_ROOT.exists():
        print(f"Repo root not found: {REPO_ROOT}")
        return 1

    notes = scan_notes()
    by_module, imports_by_file = _build_import_index(notes)
    test_pairs = _pair_tests_to_sources(notes, by_module)

    write_home(notes)
    write_user_paths(notes)
    write_repo_by_folder(notes)
    write_by_phase(notes)
    write_by_topic(notes)
    write_by_type(notes)
    write_code_by_layer(notes)
    write_code_modules(notes, by_module, imports_by_file, test_pairs)
    write_code_imports(notes, by_module, imports_by_file)
    write_test_map(notes, test_pairs)
    write_recent(notes)
    write_obsidian_config()

    doc_count = sum(1 for note in notes if note.kind == "doc")
    code_count = sum(1 for note in notes if note.kind == "code")
    print(
        f"Indexed {doc_count} docs and {code_count} code files. "
        f"MOCs -> {MOC_DIR}; config -> {VAULT_CONFIG_DIR}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
